from __future__ import annotations
import json
from pydoc import describe
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator


class BaseResponseFormat(BaseModel):
    """Base class for response formats.
    
    This class provides a common interface for all response formats,
    allowing for easy concatenation of attributes into a single string.
    """
    
    class Config:
        extra = "forbid"  # 这会在JSON Schema中设置 additionalProperties: false
    
    def info(self) -> str:
        """
        Concatenate all attributes into a single string.
        Subclasses can override this method to customize concatenation logic.
        
        Returns:
            str: The concatenated string
        """
        attributes = []
        for field_name, field_value in self.model_dump().items():
            if isinstance(field_value, (str, int, float, bool)):
                attributes.append(f"{field_name}: {field_value}")
            elif isinstance(field_value, list):
                attributes.append(f"{field_name}: {', '.join(map(str, field_value))}")
            elif isinstance(field_value, dict):
                dict_str = ', '.join([f"{k}: {v}" for k, v in field_value.items()])
                attributes.append(f"{field_name}: {{{dict_str}}}")
            elif field_value is not None:
                attributes.append(f"{field_name}: {str(field_value)}")
        
        return "\n".join(attributes)

    @classmethod
    def json_info(cls) -> str:
        """
        Return the JSON Schema of this response format as a plain text string.
        """
        schema = cls.model_json_schema()
        return json.dumps(schema, ensure_ascii=False, indent=2)

class ImplementationSpec(BaseResponseFormat):
    """String-only, uniform across ByteSized32 / CWMB / Text2World."""
    goal_and_evaluation: str = Field(..., description="(1) Success / failure / scoring.")
    objects_and_class_model: str = Field(..., description="(2) Core objects/classes + hierarchy/containment.")
    key_numbers: str = Field(..., description="(3) Units / ranges / thresholds / device params / step limit.")
    dynamics_transition: str = Field(..., description="(4) Per-tick/turn update rules, clamps, RNG & seed policy.")
    actions_and_preconditions: str = Field(..., description="(5) Action set, guards/preconditions, errors, distractors.")
    interface_contract: str = Field(..., description="(6) Class/method signatures, step() return order, observation, determinism.")

    @field_validator("*")
    @classmethod
    def _non_empty(cls, v: str) -> str:
        if not isinstance(v, str) or not v.strip():
            raise ValueError("field must be a non-empty string")
        return v.strip()

class TestPlanSimple(BaseResponseFormat):
    """Testing blueprint as plain strings."""
    happy_path: str = Field(..., description="Steps that should succeed end-to-end")
    edge_cases: str = Field(..., description="Negative/boundary scenarios that must fail or be guarded")
    assertions: str = Field(..., description="Contract checks: return order/types, determinism, invariants")

    @field_validator("*")
    @classmethod
    def _non_empty(cls, v: str) -> str:
        if not isinstance(v, str) or not v.strip():
            raise ValueError("field must be a non-empty string")
        return v.strip()

class WorldModelReport(BaseResponseFormat):
    """Minimal uniform report (no adapters, no benchmark profile)."""
    implementation_spec: str = Field(..., description="Points 1–6 for Code Agent.")
    test_plan: str  = Field(..., description="Point 7 for test/eval agents.")

    
    
class CodeReport(BaseResponseFormat):
    code_file_path: str = Field(..., description='Saved entrypoint file path')
    entrypoint_code: str = Field(..., description='Complete code content of the entrypoint')

class PlayReport(BaseResponseFormat):
    success: bool = Field(
        ...,
        description=(
            'True only if the evaluator (play_env) completed without exceptions '
            'AND met the acceptance criteria from the test plan (e.g., full traversal, '
            'no invariant violations, no time/step limit breaches).'
        ),
    )


class ResearchReport(BaseResponseFormat):
    """Structured output format for the Research agent, containing three standardized path modules:
    1. research_report_path: path to the research agent's report file (string)
    2. python_code_path: path to the Python code file generated by the research agent (string)
    3. env_state_desc_path: path to the JSON data file describing the environment state generated by the research agent (string)
    """
    research_report_content: str = Field(..., description="content of the research agent's report file (string)")

    
    @field_validator("*")
    @classmethod
    def _non_empty_path(cls, v: str) -> str:
        if not isinstance(v, str) or not v.strip():
            raise ValueError("path must be a non-empty string")
        return v.strip()
    
    def info(self) -> str:
        """
        Return a string representation of the ResearchReport object.
        
        Returns:
            str: A string containing the paths to the research report, Python code, and environment state description.
        """
        return f"Research Report Content: {self.research_report_content}\n"

class ResearchPlanReport(BaseResponseFormat):
    """Structured output format for the Research agent, containing three standardized path modules:
    1. research_report_path: path to the research agent's report file (string)
    2. python_code_path: path to the Python code file generated by the research agent (string)
    3. env_state_desc_path: path to the JSON data file describing the environment state generated by the research agent (string)
    """
    research_report_path: str = Field(..., description="path to the research agent's report file (string)")
    tools_simulation_plan_path: str = Field(..., description="path to the tools simulation report file generated by the research agent (string)")
    @field_validator("*")
    @classmethod
    def _non_empty_path(cls, v: str) -> str:
        if not isinstance(v, str) or not v.strip():
            raise ValueError("path must be a non-empty string")
        return v.strip()
    
    def info(self) -> str:
        """
        Return a string representation of the ResearchReport object.
        
        Returns:
            str: A string containing the paths to the research report, Python code, and environment state description.
        """
        return f"Research Report Path: {self.research_report_path}\nTools Simulation Plan Path: {self.tools_simulation_plan_path}\n"

class DatasetsReport(BaseResponseFormat):
    """
    python_code_path: str = Field(..., description="path to the Python code file generated by the research agent (string)")
    env_state_desc_path: str = Field(..., description="path to the JSON data file describing the environment state generated by the research agent (string)")
    requirements_path: str = Field(..., description="path to the requirements.txt file generated by the research agent (string)")
    
    """
    python_code_path: str = Field(..., description="path to the Python code file generated by the research agent (string)")
    env_state_desc_path: str = Field(..., description="path to the JSON data file describing the environment state generated by the research agent (string)")
    requirements_path: str = Field(..., description="path to the requirements.txt file generated by the research agent (string)")
    
    def info(self) -> str:
        """
        A class representing a response format for code generation.
        """
        return f"""
        The dataclass code generation file path : {self.python_code_path}
    
    """

class EnvStateReport(BaseResponseFormat):
    """
    python_code_path: str = Field(..., description="path to the Python code file generated by the research agent (string)")
    env_state_desc_path: str = Field(..., description="path to the JSON data file describing the environment state generated by the research agent (string)")
    requirements_path: str = Field(..., description="path to the requirements.txt file generated by the research agent (string)")
    
    """
    env_state_desc_path: str = Field(..., description="path to the JSON data file describing the environment state generated by the research agent (string)")
    user_profile_path: str = Field(..., description="path to the JSON data file describing the user profile generated by the research agent (string)")
    
    def info(self) -> str:
        """
        A class representing a response format for code generation.
        """
        return f"""
        The environment state code generation file path : {self.env_state_desc_path}
        The user profile code generation file path : {self.user_profile_path}
    
    """


class CodeGenReport(BaseResponseFormat):
    code_path: str = Field(..., description="path to the generated code file (string)")

class PytestReport(BaseResponseFormat):
    success: bool = Field(
        ...,
        description=(
            'True iff pytest exit_code == 0 (all tests collected and passed with no hard errors).'
        ),
    )
    analysis: str = Field(
        default=None,
        description=(
            'Short human-readable diagnosis (≈3–6 sentences): group failures by cause, '
            'highlight the first failing assertion for each group, and summarize the likely fix. '
            'Include the most relevant nodeid(s); avoid dumping full tracebacks.'
        ),
    )
    suggest_fix: str = Field(
        default=None,
        description=(
            'Concrete, minimal corrective steps to make tests pass. Use small bullets referencing '
            'specific functions/branches/conditions; include rationale and any contract/invariant '
            'that the change restores.'
        ),
    )

class Task(BaseResponseFormat):
    task_description: str = Field(..., description="A single natural-language question that implicitly requires the tools.")
    tools: List[str] = Field(..., description="A list of tools that can be used to answer the task.")

class ListTask(BaseResponseFormat):
    tasks: List[Task] = Field(..., description="A list of tasks.")
    
    def info(self) -> str:
        """
        Return a string representation of the ListTask object.
        
        Returns:
            str: A string containing the descriptions of all tasks.
        """
        return "\n".join([f"Task: {task.task_description}" for task in self.tasks])
    def to_json(self) -> str:
        """
        Convert the ListTask object to a JSON string.
        
        Returns:
            str: A JSON string representation of the ListTask object.
        """
        return json.dumps(self.dict())

class TaskTrajectoryScore(BaseResponseFormat):
    class BaseScore(BaseResponseFormat):
        reasoning: str = Field(..., description="Reasoning for the score.")
        score: float = Field(..., description="Score value.")
    
    completeness: BaseScore = Field(...)
    conciseness: BaseScore = Field(...)
    overall_score: float = Field(..., description="Overall score.")
    desired_tools_used_percentage: float = Field(..., description="Percentage of desired tools used.")

class SeedTaskItem(BaseResponseFormat):
    name: str = Field(..., description="Task name")
    description: str = Field(..., description="Task description")
    tools: List[str] = Field(..., description="Tools used to solve the task")
    tool_analysis: str = Field(..., description="Brief analysis of tool selection and usage")

class InitAndSeedTasks(BaseResponseFormat):
    init_state: str = Field(..., description="Initialization state object for the server (stringified JSON)")
    seed_tasks: List[SeedTaskItem] = Field(..., description="List of seed tasks with tool info and analysis")
    domain_mode: str = Field(..., description="Domain mode classification: 'fixed_domain' or 'general_tool'")

    @field_validator("init_state")
    @classmethod
    def _coerce_init_state(cls, v: Any) -> str:
        if isinstance(v, str):
            return v.strip()
        try:
            return json.dumps(v or {}, ensure_ascii=False)
        except Exception:
            return json.dumps({}, ensure_ascii=False)

    @field_validator("domain_mode")
    @classmethod
    def _validate_domain_mode(cls, v: Any) -> str:
        if isinstance(v, str):
            s = v.strip().lower()
            if s in ("fixed_domain", "general_tool"):
                return s
        return "general_tool"

class ScoreAnalysis(BaseResponseFormat):
    score: int = Field(..., description="Score from 1 to 5")
    analysis: str = Field(..., description="Short explanation")

    @field_validator("score")
    @classmethod
    def _validate_score(cls, v: int) -> int:
        if not isinstance(v, int):
            raise ValueError("score must be an integer")
        if v < 1 or v > 5:
            raise ValueError("score must be between 1 and 5")
        return v

    @field_validator("analysis")
    @classmethod
    def _non_empty_analysis(cls, v: str) -> str:
        if not isinstance(v, str) or not v.strip():
            raise ValueError("analysis must be a non-empty string")
        return v.strip()

class Feedback(BaseResponseFormat):
    init_state_quality: ScoreAnalysis = Field(..., description="Init state quality score and analysis")
    tool_alignment: ScoreAnalysis = Field(..., description="Target tool alignment score and analysis")
    tool_selection_difficulty: ScoreAnalysis = Field(..., description="Difficulty of selecting the correct tool")
    task_quality_realism: ScoreAnalysis = Field(..., description="Question quality and scenario realism")
    verifiability_stability: ScoreAnalysis = Field(..., description="Verifiability and stability")
    fission_potential: ScoreAnalysis = Field(..., description="Seed suitability for generating variants")
    overall: ScoreAnalysis = Field(..., description="Overall score and summary analysis")

class RewriteResult(BaseResponseFormat):
    question: str = Field(..., description="Rewritten task description")

class ConstraintsResult(BaseResponseFormat):
    question: str = Field(..., description="Harder task description")
    constraints: str = Field(default="", description="Added constraints for increasing difficulty (stringified JSON)")

    @field_validator("constraints")
    @classmethod
    def _coerce_constraints(cls, v: Any) -> str:
        if isinstance(v, str):
            return v.strip()
        try:
            return json.dumps(v or {}, ensure_ascii=False)
        except Exception:
            return ""

class InitStateTasksVariant(BaseResponseFormat):
    init_state: str = Field(..., description="Initialization state for the variant (stringified JSON)")
    seed_tasks: List[SeedTaskItem] = Field(..., description="Diversified tasks for the variant")

    @field_validator("init_state")
    @classmethod
    def _coerce_variant_init_state(cls, v: Any) -> str:
        if isinstance(v, str):
            return v.strip()
        try:
            return json.dumps(v or {}, ensure_ascii=False)
        except Exception:
            return json.dumps({}, ensure_ascii=False)

class DiversityVariants(BaseResponseFormat):
    variants: List[InitStateTasksVariant] = Field(..., description="List of diversified init_state + task sets")

class TaskJudge(BaseResponseFormat):
    score: int = Field(..., description="Score from 1 to 5")
    analysis: str = Field(..., description="Explanation for the score")

class McpServerFilePath(BaseResponseFormat):
    file_path: str = Field(..., description="Path to the MCP server file")